name: Build ESPHome Cloud

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Git and ESPHome
        run: |
          sudo apt-get update
          sudo apt-get install -y git
          pip install platformio
          pip install esphome

      - name: Compile Firmware
        run: |
          esphome compile alpicool.yaml

      - name: Upload Firmware File
        uses: actions/upload-artifact@v4
        with:
          name: alpicool-fridge-firmware
          path: .esphome/build/alpicool-fridge/.pioenvs/alpicool-fridge/firmware.bin
